#!/bin/bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE DATABASE $AUTH_DB_NAME;
  REVOKE connect ON DATABASE $AUTH_DB_NAME FROM PUBLIC;
  CREATE DATABASE $POSTS_DB_NAME;
  REVOKE connect ON DATABASE $POSTS_DB_NAME FROM PUBLIC;
  CREATE DATABASE $AGENT_DB_NAME;
  REVOKE connect ON DATABASE $AGENT_DB_NAME FROM PUBLIC;

  REVOKE connect ON DATABASE postgres FROM PUBLIC;
  REVOKE connect ON DATABASE root FROM PUBLIC;
  
  CREATE USER $AUTH_DB_USER WITH PASSWORD '$AUTH_DB_PASS';
  GRANT ALL PRIVILEGES ON DATABASE $AUTH_DB_NAME TO $AUTH_DB_USER;
  
  CREATE USER $POSTS_DB_USER WITH PASSWORD '$POSTS_DB_PASS';
  GRANT ALL PRIVILEGES ON DATABASE $POSTS_DB_NAME TO $POSTS_DB_USER;

  CREATE USER $AGENT_DB_USER WITH PASSWORD '$AGENT_DB_PASS';
  GRANT ALL PRIVILEGES ON DATABASE $AGENT_DB_NAME TO $AGENT_DB_USER;
EOSQL