version: "3.8"

services:
  dislinkt-gateway:
    image: ghcr.io/dislinkt-devops/dislinkt-gateway-api:latest
    ports:
      - 3000:3000
  db:
    image: postgres:14.1-alpine
    restart: always
    env_file: 
      - .env
    ports: 
      - 5432:5432
    volumes:
      - ./database/init/01-init-psql.sh:/docker-entrypoint-initdb.d/01-init-psql.sh
  mongodb:
    image: mongo:5.0
    restart: always
    ports:
      - 27017:27017
    env_file: 
      - .env
    volumes:
      - ./database/init/01-init-mongo.sh:/docker-entrypoint-initdb.d/01-init-mongo.sh
volumes:
  db:
    driver: local